//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnkietaAlkoholowa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Records
    {
        public int id { get; set; }
        public int age { get; set; }
        public string sex { get; set; }
        public string education { get; set; }
        public string live { get; set; }
        public string kind { get; set; }
        public string times { get; set; }
        public string place { get; set; }
        public bool aggresive { get; set; }
        public bool addiction { get; set; }
        public bool hangover { get; set; }
    }
}
